# Generated by Django 4.2 on 2023-08-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="is_blogger",
            field=models.BooleanField(default=False),
        ),
    ]
