# Generated by Django 4.2 on 2023-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_details", "0002_userdetails_is_blogger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloginfo",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="media/blog_imgs"),
        ),
    ]
